import { rest } from 'msw';
import { setupServer } from 'msw/node';

export default function Mswsetupserver() {
  return setupServer(
    // capture 'GET /greeting' requests

    rest.get('https://themealdb.p.rapidapi.com/search.php', (req, res, ctx) => res(
      ctx.delay(500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        meals: [
          {
            idMeal: '52959',
            strMeal: 'Baked salmon with fennel & tomatoes',
            strMealThumb: 'https://www.themealdb.com/images/media/meals/1548772327.jpg',
          },
        ],
      }),
    )),
    rest.get('https://themealdb.p.rapidapi.com/lookup.php', (req, res, ctx) => res(
      ctx.delay(500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        meals: [
          {
            dateModified: 'NULL',
            idMeal: '52772',
            strArea: 'Japanese',
            strCategory: 'Chicken',
            strDrinkAlternate: 'NULL',
            strIngredient1: 'soy sauce',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: 'NULL',
            strIngredient17: 'NULL',
            strIngredient18: 'NULL',
            strIngredient19: 'NULL',
            strIngredient2: 'water',
            strIngredient20: 'NULL',
            strIngredient3: 'brown sugar',
            strIngredient4: 'ground ginger',
            strIngredient5: 'minced garlic',
            strIngredient6: 'cornstarch',
            strIngredient7: 'chicken breasts',
            strIngredient8: 'stir-fry vegetables',
            strIngredient9: 'brown rice',
            strInstructions: 'Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray. Combine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling. Meanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat. Place the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks. *Meanwhile, steam or cook the vegetables according to package directions. Add the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!',
            strMeal: 'Teriyaki Chicken Casserole',
            strMealThumb: 'https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg',
            strMeasure1: '3/4 cup',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: 'NULL',
            strMeasure17: 'NULL',
            strMeasure18: 'NULL',
            strMeasure19: 'NULL',
            strMeasure2: '1/2 cup',
            strMeasure20: 'NULL',
            strMeasure3: '1/4 cup',
            strMeasure4: '1/2 teaspoon',
            strMeasure5: '1/2 teaspoon',
            strMeasure6: '4 Tablespoons',
            strMeasure7: '2',
            strMeasure8: '1 (12 oz.)',
            strMeasure9: '3 cups',
            strSource: 'NULL',
            strTags: 'Meat,Casserole',
            strYoutube: 'https://www.youtube.com/watch?v=4aZr5hZXP_s',
          },
        ],
      }),
    )),
    rest.get('https://themealdb.p.rapidapi.com/list.php', (req, res, ctx) => res(
      ctx.delay(500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        meals: [{
          strCategory: 'Beef',
        }, {
          strCategory: 'Beef 1',
        }, {
          strCategory: 'Beef 2',
        }],
      }),
    )),
    rest.get('https://themealdb.p.rapidapi.com/filter.php', (req, res, ctx) => res(
      ctx.delay(500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        meals: [
          {
            idMeal: '52959',
            strMeal: 'Baked salmon with fennel & tomatoes',
            strMealThumb: 'https://www.themealdb.com/images/media/meals/1548772327.jpg',
          },
        ],
      }),
    )),
    rest.get('https://themealdb.p.rapidapi.com/latest.php', (req, res, ctx) => res(
      ctx.delay(500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        meals: [
          {
            dateModified: 'NULL',
            idMeal: '52772',
            strArea: 'Japanese',
            strCategory: 'Chicken',
            strDrinkAlternate: 'NULL',
            strIngredient1: 'soy sauce',
            strIngredient10: '',
            strIngredient11: '',
            strIngredient12: '',
            strIngredient13: '',
            strIngredient14: '',
            strIngredient15: '',
            strIngredient16: 'NULL',
            strIngredient17: 'NULL',
            strIngredient18: 'NULL',
            strIngredient19: 'NULL',
            strIngredient2: 'water',
            strIngredient20: 'NULL',
            strIngredient3: 'brown sugar',
            strIngredient4: 'ground ginger',
            strIngredient5: 'minced garlic',
            strIngredient6: 'cornstarch',
            strIngredient7: 'chicken breasts',
            strIngredient8: 'stir-fry vegetables',
            strIngredient9: 'brown rice',
            strInstructions: 'Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray. Combine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling. Meanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat. Place the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks. *Meanwhile, steam or cook the vegetables according to package directions. Add the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!',
            strMeal: 'Teriyaki Chicken Casserole',
            strMealThumb: 'https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg',
            strMeasure1: '3/4 cup',
            strMeasure10: '',
            strMeasure11: '',
            strMeasure12: '',
            strMeasure13: '',
            strMeasure14: '',
            strMeasure15: '',
            strMeasure16: 'NULL',
            strMeasure17: 'NULL',
            strMeasure18: 'NULL',
            strMeasure19: 'NULL',
            strMeasure2: '1/2 cup',
            strMeasure20: 'NULL',
            strMeasure3: '1/4 cup',
            strMeasure4: '1/2 teaspoon',
            strMeasure5: '1/2 teaspoon',
            strMeasure6: '4 Tablespoons',
            strMeasure7: '2',
            strMeasure8: '1 (12 oz.)',
            strMeasure9: '3 cups',
            strSource: 'NULL',
            strTags: 'Meat,Casserole',
            strYoutube: 'https://www.youtube.com/watch?v=4aZr5hZXP_s',
          },
        ],
      }),
    )),

  );
}
